### ISSUE TITLE
Việc tạo ra hai biến dong và n có mục đích gì vậy bạn ? Không phải nó là như nhau à

### ISSUE THREAD

**Issue by toniminh161200** [thtrangphu/code_online#1]
https://github.com/thtrangphu/code_online/blob/5ada49b64246b40cb65041df5233bba9221a0f5f/Source.cpp#L12

**Comment by thtrangphu** [comment]
dạ anh ơi, 
![image](https://user-images.githubusercontent.com/76843467/111862998-55ed3300-898b-11eb-9ad0-0bc8efeeee5f.png)
em có dùng đấy ạ, vì em muốn biến n cố định còn biến dòng là để thay đổi chẳng hạn dong-- đó ạ

**Comment by toniminh161200** [comment]
Mình cũng có hiểu ý đồ của bạn. Nhưng bạn thử nghĩ cách nào để không cần phải sử dụng tới biến `dong` kia.
