### ISSUE TITLE
?????? Liệu bạn dùng cách này có thể in ra được học lực tương ứng với điểm hay không ?

### ISSUE THREAD

**Issue by toniminh161200** [thtrangphu/code_online#13]
https://github.com/thtrangphu/code_online/blob/6ac2553947d88f3b2e4f6eb8481d39cde9a13f84/bai2.cpp#L23-L25

**Comment by thtrangphu** [comment]
có mà anh, anh có thể check lại ạ

**Comment by toniminh161200** [comment]
Bạn đang cho mặc định x = 0 mà ? Với các trường hợp khác thfi sao ?

**Comment by thtrangphu** [comment]
anh chạy thử đi ạ

**Comment by toniminh161200** [comment]
Mình chạy rồi nhưng mà tại sao bạn lại để x = 0 thế kia ? Với lại mục đích bạn dùng tham chiếu ở đây để làm gì ? Mình chưa hiểu ý ở đây lắm ??

**Comment by thtrangphu** [comment]
x=0 là để khởi tạo ô nhớ cho x còn tham chiếu là thay đổi giá trị của biến x, chương trình của em nó đâu có sai chỗ nào đâu ạ

**Comment by toniminh161200** [comment]
Tại sao lại phải khởi tạo ô nhớ tại đây ?

**Comment by thtrangphu** [comment]
Kiểu để int x; không thì vẫn đúng nhưng em theo thói quen của giáo viên trên lớp để 0 nên e cũng để luôn ạ

**Comment by thtrangphu** [comment]
nếu int x thì nó giống như NULL chưa có giá trị

**Comment by toniminh161200** [comment]
Có thể một ý tưởng hay. Cảm ơn bạn vì đã đưa ra cho mình thêm một kiến thức mới. Nhưng mà theo quan điểm của mình vì biến x này của bạn đang được sử dụng (chứ nó k phải sử dụng tức là chỉ việc khai báo 
```C++
 int x
```
rồi vứt tại chỗ đó). Tốt nhất bạn k nên cập nhật giá trị tại x = 0 vì lúc đó có thể gây ra nhiều hiểu nhầm cho mình ngay từ lúc đầu. Btw, thanks bạn nhiều
