### ISSUE TITLE
Thêm số 0 vào trước số hoàn thiện thì tại sao khi bạn gọi hàm này thì lại k cập nhật giá trị của x hửm ?

### ISSUE THREAD

**Issue by toniminh161200** [thtrangphu/code_online#29]
https://github.com/thtrangphu/code_online/blob/654d4909c321cc958e3be2767e230e321f938f30/Bai2.cpp#L40

**Comment by thtrangphu** [comment]
![image](https://user-images.githubusercontent.com/76843467/112866810-65cfea00-90e4-11eb-9569-6b7d9322b66c.png)
Bởi vì em muốn dùng hàm đó nhiều lần nên lúc hàm ở dưới em gọi ra thì vẫn để x=0 đấy ạ.

**Comment by toniminh161200** [comment]
Nhưng tiếc rằng khi mình test thử chương trình bạn thì nó không ra đúng việc thêm các số 0 vào trước các số hoàn thiện bạn à :(

**Comment by thtrangphu** [comment]
cho em xin test case của anh ạ

**Comment by thtrangphu** [comment]
![image](https://user-images.githubusercontent.com/76843467/112868775-a2044a00-90e6-11eb-835c-2e81dacf3023.png)
do em thấy em test vẫn bình thường, chắc là có một vài trường hợp sai, nên em muốn tham khảo test case của anh để sửa code cho hoàn thiện thêm ạ

**Comment by toniminh161200** [comment]
6972593
<img width="483" alt="image" src="https://user-images.githubusercontent.com/52942703/112869111-fc050f80-90e6-11eb-998b-7b6d850b0e46.png">

**Comment by toniminh161200** [comment]
https://vi.wikipedia.org/wiki/S%E1%BB%91_ho%C3%A0n_thi%E1%BB%87n - hmmm
có lẽ ở trong wiki test bị lỗi nhỉ

**Comment by toniminh161200** [comment]
Mình chỉ lấy test mẫu về số hoàn thiện trong wiki thôi
